
spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      p6spy: true # 默认false,建议线上关闭。
      druid: #以下是全局默认值，可以全局更改
        minIdle: 5
        maxActive: 20
        filters: stat,wall # 注意这个值和druid原生不一致，默认启动了stat,wall
        stat:
          merge-sql: true
          log-slow-sql: true
      datasource:
        master:
          username: dev
          password: dev
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.14.115:3306/BusinessLog?characterEncoding=utf8&useSSL=true
        prizeConfig:
          username: dev
          password: dev
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.28.14.115:3306/topicdb?characterEncoding=utf8&useSSL=true
logback:
  appName: user-service
  logDir: logs/user-service




server:
  port: 8033
