spring:
  application:
    name: user-service
logging:
  level:
    com.wuyd.acp.oauthservice: debug
  file:
    total-size-cap: 2GB
    name: ${logging.file.path}/user-service.log
    path: logs
    max-size: 10MB
    max-history: 30
  pattern:
    rolling-file-name: ${logging.file.path}/user-service.%d{yyyy-MM-dd}-%i.log
server:
  port: 8033
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-service:8031/eureka-service/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
    prefer-ip-address: true

security:
  oauth2:
    resource:
      id: user-service
      user-info-uri: http://localhost:8034/auth/api/member
      prefer-token-info: false
