server:
  port: 8034
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@eureka-service:8031/eureka-service/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: localhost
    prefer-ip-address: true

spring:
  application:
    name: zuul-service
#--------------------Zuul-----------------------
zuul:
  routes:
    member:
      path: /user/**
      serviceId: user-service
      sensitiveHeaders: "*"
    auth:
      path: /auth/**
      serviceId: auth-service
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  add-proxy-headers: true
#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://localhost:${server.port}/auth/api/member
      prefer-token-info: false
logging:
  level:
    com.wuyd.acp.oauthservice: debug
  file:
    total-size-cap: 2GB
    name: ${logging.file.path}/zuul-service.log
    path: logs
    max-size: 10MB
    max-history: 30
  pattern:
    rolling-file-name: ${logging.file.path}/zuul-service.%d{yyyy-MM-dd}-%i.log