spring:
  application:
    name: eureka-service
  profiles:
    active: @profileActive@
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    use-dns-for-fetching-service-urls: false
  instance:
    instance-id: SERVER_${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
server:
  servlet:
    context-path: /eureka-service
